name: Auto Repost Facebook

on:
  schedule:
    - cron: "0 */4 * * *"  # Cada 4 horas
  workflow_dispatch:       # Permite ejecución manual

jobs:
  repost:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Instalar dependencias
        run: pip install requests python-dotenv

      - name: Ejecutar script
        env:
          LU17_ACCESS_TOKEN: ${{ secrets.LU17_ACCESS_TOKEN }}
          TRELEW_ACCESS_TOKEN: ${{ secrets.TRELEW_ACCESS_TOKEN }}
          LU17_PAGE_ID: ${{ secrets.LU17_PAGE_ID }}
          TRELEW_PAGE_ID: ${{ secrets.TRELEW_PAGE_ID }}
        run: python main.py

      - name: Guardar nuevos IDs si hubo publicaciones
        if: success()
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          if [ -n "$(git status --porcelain)" ]; then
            git add last_post.txt
            git commit -m "📌 Actualizar lista de publicaciones compartidas"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
          else
            echo "No hay cambios para guardar."
